# Generated by Django 2.2.2 on 2019-06-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20190615_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.ExpenseAccount'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.ExpenseCategory'),
        ),
    ]
