# Generated by Django 2.2.2 on 2019-06-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20190616_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.ExpenseAccount'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.CharField(max_length=200, verbose_name='Amount'),
        ),
    ]
