# Generated by Django 2.2.2 on 2019-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20190616_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
