# Generated by Django 2.2.2 on 2019-06-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_auto_20190616_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='category',
        ),
    ]
