# Generated by Django 2.2.2 on 2019-06-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_remove_expenseitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='account',
        ),
    ]
