# Generated by Django 2.2.2 on 2019-06-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_remove_expenseitem_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.ExpenseAccount'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.ExpenseCategory'),
        ),
    ]
