# Generated by Django 2.2.2 on 2019-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20190616_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
    ]
