# Generated by Django 2.2.2 on 2019-06-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'ExpenseCategories'},
        ),
    ]
